name: temp_project
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.15
  get_it: ^8.0.2
  shared_preferences: ^2.3.3
  shimmer_animation: ^2.2.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria.ttf